# Generated by Django 4.2.5 on 2023-10-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bId', models.CharField(max_length=50)),
                ('bName', models.CharField(max_length=50)),
                ('bAuthor', models.CharField(max_length=20)),
                ('bPublish', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'bookms',
            },
        ),
    ]
